version: '2.1'
services:

  todo-db:
    image: postgres:latest
    container_name: todo-db
    restart: always
    ports:
      - "5436:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data